apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    custom: myApp
  name: placement-red-hat-cloud
  namespace: my-policies
spec:
  clusterSelector:
    matchExpressions:
      - key: cloud
        operator: In
        values:
          - red hat
