apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
- ./policyGenerator.yaml
- ./policyGenerator-kustomize.yaml

patches:
- path: input/patch.yaml

labels:
- includeSelectors: true
  pairs:
    custom: myApp
